import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{LayoutDashboard,ArrowLeftRight,WalletCards,ChartPie,Target,Settings,Plus,Search,Bell,TrendingUp,TrendingDown,Eye,EyeOff,X,ShoppingBag,Utensils,Car,HeartPulse,MoreHorizontal,Repeat2,Trash2,LogOut,CheckCircle2}from'lucide-react';
import'./style.css';

const nav=[['Visão geral',LayoutDashboard],['Lançamentos',ArrowLeftRight],['Contas e cartões',WalletCards],['Planejamento',ChartPie],['Metas',Target]];
const iconMap={food:Utensils,wallet:WalletCards,car:Car,shop:ShoppingBag,health:HeartPulse};
const money=(v,c='EUR')=>new Intl.NumberFormat(c==='EUR'?'pt-PT':'pt-BR',{style:'currency',currency:c}).format(Number(v)||0);
const today=()=>new Intl.DateTimeFormat('pt-PT',{day:'2-digit',month:'short',year:'numeric'}).format(new Date());
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};

function Empty({icon:Icon=ArrowLeftRight,title,text,action,onAction}){return <div className="empty"><div><Icon size={25}/></div><h3>{title}</h3><p>{text}</p>{action&&<button className="new" onClick={onAction}><Plus size={17}/>{action}</button>}</div>}
function FinanceApp({onLogout}){
 const[page,setPage]=useState('Visão geral'),[modal,setModal]=useState(null),[search,setSearch]=useState('');
 const[tx,setTx]=useState(()=>load('mf-transactions-v3',[])),[accounts,setAccounts]=useState(()=>load('mf-accounts-v3',[])),[goals,setGoals]=useState(()=>load('mf-goals-v3',[])),[budgets,setBudgets]=useState(()=>load('mf-budgets-v3',[])),[show,setShow]=useState(true);
 useEffect(()=>localStorage.setItem('mf-transactions-v3',JSON.stringify(tx)),[tx]);useEffect(()=>localStorage.setItem('mf-accounts-v3',JSON.stringify(accounts)),[accounts]);useEffect(()=>localStorage.setItem('mf-goals-v3',JSON.stringify(goals)),[goals]);useEffect(()=>localStorage.setItem('mf-budgets-v3',JSON.stringify(budgets)),[budgets]);
 const eurValue=t=>t.currency==='BRL'?t.value/(t.rate||1):t.value,income=useMemo(()=>tx.filter(x=>x.type==='in').reduce((s,x)=>s+eurValue(x),0),[tx]),expense=useMemo(()=>tx.filter(x=>x.type==='out').reduce((s,x)=>s+eurValue(x),0),[tx]),filtered=tx.filter(t=>(t.name+' '+t.cat).toLowerCase().includes(search.toLowerCase()));
 function saveTransaction(e){e.preventDefault();let f=new FormData(e.currentTarget),currency=f.get('currency'),value=Number(f.get('value')),rate=Number(f.get('rate'))||1;setTx([{id:Date.now(),date:today(),name:f.get('name'),cat:f.get('cat'),type:f.get('type'),value,currency,rate:currency==='BRL'?rate:null,icon:f.get('type')==='in'?'wallet':'shop'},...tx]);setModal(null)}
 function saveSimple(e,type){e.preventDefault();let f=new FormData(e.currentTarget),item={id:Date.now(),name:f.get('name'),value:Number(f.get('value'))||0};if(type==='account')setAccounts([...accounts,item]);if(type==='goal')setGoals([...goals,item]);if(type==='budget')setBudgets([...budgets,item]);setModal(null)}
 return <div className="app"><aside><div className="brand"><span>m</span><b>Meu Fluxo</b></div><nav>{nav.map(([n,I])=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}><I size={19}/>{n}</button>)}</nav><div className="aside-bottom"><div className="tip"><b>Comece do seu jeito</b><small>Sua base está limpa e pronta para os primeiros registros.</small><button onClick={()=>setModal('transaction')}>Criar lançamento</button></div><button className={page==='Configurações'?'active':''} onClick={()=>setPage('Configurações')}><Settings size={19}/>Configurações</button><div className="profile"><div>JS</div><span><b>Julio</b><small>Conta pessoal</small></span><MoreHorizontal size={18}/></div></div></aside>
 <main><header><div><h1>{page}</h1><p>{today()}</p></div><div className="header-actions"><div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar lançamentos..."/></div><button className="iconbtn" aria-label="Notificações"><Bell size={19}/></button><button className="currency-view" onClick={()=>setModal('converter')}><Repeat2 size={16}/><span>EUR</span><small>Ver em BRL</small></button><button className="new" onClick={()=>setModal('transaction')}><Plus size={18}/>Novo lançamento</button></div></header>
 <section className="content">{page==='Visão geral'&&<Overview income={income} expense={expense} tx={filtered} show={show} setShow={setShow} open={()=>setModal('transaction')} go={setPage}/>} {page==='Lançamentos'&&<Transactions tx={filtered} remove={id=>setTx(tx.filter(t=>t.id!==id))} open={()=>setModal('transaction')}/>} {page==='Contas e cartões'&&<Collection title="Contas e cartões" text="Organize onde seu dinheiro fica. Os saldos são registrados em euro." items={accounts} open={()=>setModal('account')} remove={id=>setAccounts(accounts.filter(x=>x.id!==id))} empty="Nenhuma conta cadastrada" icon={WalletCards}/>} {page==='Planejamento'&&<Collection title="Planejamento mensal" text="Defina limites em euro para acompanhar seus gastos." items={budgets} open={()=>setModal('budget')} remove={id=>setBudgets(budgets.filter(x=>x.id!==id))} empty="Nenhum limite planejado" icon={ChartPie}/>} {page==='Metas'&&<Collection title="Metas financeiras" text="Crie objetivos e acompanhe quanto falta para realizá-los." items={goals} open={()=>setModal('goal')} remove={id=>setGoals(goals.filter(x=>x.id!==id))} empty="Nenhuma meta cadastrada" icon={Target}/>} {page==='Configurações'&&<Config onLogout={onLogout}/>}</section></main>
 {modal==='transaction'&&<TransactionModal save={saveTransaction} close={()=>setModal(null)}/>} {modal==='converter'&&<Converter close={()=>setModal(null)}/>} {['account','goal','budget'].includes(modal)&&<SimpleModal type={modal} save={e=>saveSimple(e,modal)} close={()=>setModal(null)}/>}</div>
}
function Overview({income,expense,tx,show,setShow,open,go}){return <><div className="welcome"><div><span>MOEDA PRINCIPAL: EURO</span><h2>Seu novo controle financeiro<br/>começa com uma base limpa.</h2></div></div><div className="cards"><Card label="Saldo total" value={income-expense} main show={show} onEye={()=>setShow(!show)}/><Card label="Receitas" value={income} show={show} up/><Card label="Despesas" value={expense} show={show}/><Card label="Economia do mês" value={income-expense} show={show} up/></div><div className="grid"><div className="panel cash"><div className="panel-head"><div><h3>Fluxo de caixa</h3><p>Preenchido conforme seus lançamentos</p></div></div>{tx.length?<MiniChart tx={tx}/>:<Empty icon={ChartPie} title="Ainda não há dados para o gráfico" text="Adicione sua primeira receita ou despesa para acompanhar a evolução." action="Novo lançamento" onAction={open}/>}</div><div className="panel categories"><div className="panel-head"><div><h3>Despesas por categoria</h3><p>Distribuição dos seus gastos</p></div></div>{tx.some(t=>t.type==='out')?<CategoryList tx={tx}/>:<Empty icon={ChartPie} title="Sem despesas" text="As categorias aparecerão aqui depois do primeiro registro."/>}</div></div><div className="panel transactions overview-list"><div className="panel-head"><div><h3>Últimos lançamentos</h3><p>Movimentações mais recentes</p></div>{tx.length>0&&<button className="link" onClick={()=>go('Lançamentos')}>Ver todos</button>}</div>{tx.length?tx.slice(0,5).map(t=><TransactionRow key={t.id} t={t}/>):<Empty title="Sua base está vazia" text="Nenhum valor de exemplo foi incluído. Cadastre o primeiro lançamento quando estiver pronto." action="Criar primeiro lançamento" onAction={open}/>}</div></>}
function Transactions({tx,remove,open}){return <div className="page-stack"><div className="page-title"><div><h2>Lançamentos</h2><p>Registre receitas e despesas em EUR ou BRL.</p></div><button className="new" onClick={open}><Plus size={18}/>Novo lançamento</button></div><div className="panel">{tx.length?tx.map(t=><TransactionRow key={t.id} t={t} remove={()=>remove(t.id)}/>):<Empty title="Nenhum lançamento cadastrado" text="A lista está limpa para você começar sua própria base." action="Novo lançamento" onAction={open}/>}</div></div>}
function Collection({title,text,items,open,remove,empty,icon:Icon}){return <div className="page-stack"><div className="page-title"><div><h2>{title}</h2><p>{text}</p></div><button className="new" onClick={open}><Plus size={18}/>Adicionar</button></div><div className="collection">{items.length?items.map(x=><div className="collection-card" key={x.id}><div className="collection-icon"><Icon/></div><div><b>{x.name}</b><small>Valor definido</small><strong>{money(x.value)}</strong></div><button className="delete" onClick={()=>remove(x.id)} aria-label="Excluir"><Trash2 size={17}/></button></div>):<div className="panel"><Empty icon={Icon} title={empty} text="Use o botão Adicionar para criar o primeiro item." action="Adicionar" onAction={open}/></div>}</div></div>}
function Config({onLogout}){return <div className="page-stack"><div className="page-title"><div><h2>Configurações</h2><p>Preferências da sua conta e segurança.</p></div></div><div className="settings-grid"><div className="panel setting"><div className="collection-icon"><Repeat2/></div><div><h3>Moeda principal</h3><p>Todos os totais e novos registros usam EUR por padrão.</p></div><strong>EUR · Euro</strong></div><div className="panel setting"><div className="collection-icon"><CheckCircle2/></div><div><h3>Base de dados</h3><p>Os registros ficam guardados somente neste navegador.</p></div><strong>Ativa</strong></div><button className="logout" onClick={onLogout}><LogOut size={18}/>Terminar sessão</button></div></div>}
function TransactionRow({t,remove}){let I=iconMap[t.icon]||ShoppingBag;return <div className="row"><div className={'cat '+t.type}><I size={18}/></div><div className="txname"><b>{t.name}</b><small>{t.cat} · {t.date}{t.currency==='BRL'?` · cotação ${t.rate}`:''}</small></div><div className="txvalue"><strong className={t.type}>{t.type==='in'?'+':'−'} {money(t.value,t.currency)}</strong>{t.currency==='BRL'&&<small>≈ {money(t.value/t.rate)}</small>}</div>{remove&&<button className="delete" onClick={remove} aria-label="Excluir lançamento"><Trash2 size={16}/></button>}</div>}
function Card({label,value,main,show,onEye,up}){return <div className={'summary '+(main?'primary':'')}><div className="label">{label}{main&&<button onClick={onEye}>{show?<Eye size={17}/>:<EyeOff size={17}/>}</button>}</div><strong>{show?money(value):'••••••'}</strong><small className={up?'positive':''}>{up?<TrendingUp size={14}/>:<TrendingDown size={14}/>} Calculado em EUR</small></div>}
function MiniChart({tx}){let inc=tx.filter(t=>t.type==='in').reduce((s,t)=>s+(t.currency==='BRL'?t.value/t.rate:t.value),0),out=tx.filter(t=>t.type==='out').reduce((s,t)=>s+(t.currency==='BRL'?t.value/t.rate:t.value),0),max=Math.max(inc,out,1);return <div className="simple-chart"><div><i style={{height:`${Math.max(4,inc/max*100)}%`}}/><span>Receitas<br/><b>{money(inc)}</b></span></div><div><i className="outbar" style={{height:`${Math.max(4,out/max*100)}%`}}/><span>Despesas<br/><b>{money(out)}</b></span></div></div>}
function CategoryList({tx}){let groups={};tx.filter(t=>t.type==='out').forEach(t=>groups[t.cat]=(groups[t.cat]||0)+(t.currency==='BRL'?t.value/t.rate:t.value));let total=Object.values(groups).reduce((a,b)=>a+b,0);return <ul className="category-list">{Object.entries(groups).sort((a,b)=>b[1]-a[1]).map(([name,value])=><li key={name}><span><i/>{name}</span><b>{Math.round(value/total*100)}%</b><small>{money(value)}</small></li>)}</ul>}
function TransactionModal({save,close}){const[currency,setCurrency]=useState('EUR');return <div className="overlay"><form className="modal" onSubmit={save}><ModalHead title="Novo lançamento" text="EUR é o padrão, mas este registro pode ser feito em BRL." close={close}/><label>Descrição<input required name="name" placeholder="Ex.: Mercado, salário..." autoFocus/></label><div className="formgrid"><label>Tipo<select name="type"><option value="out">Despesa</option><option value="in">Receita</option></select></label><label>Moeda<select name="currency" value={currency} onChange={e=>setCurrency(e.target.value)}><option value="EUR">EUR — Euro</option><option value="BRL">BRL — Real brasileiro</option></select></label></div><label>Valor ({currency})<input required name="value" type="number" min="0.01" step="0.01" placeholder="0,00"/></label>{currency==='BRL'&&<label>Cotação usada (1 EUR em BRL)<input required name="rate" type="number" min="0.01" step="0.0001" placeholder="Ex.: 6,20"/><small>Usaremos esta cotação para incluir o lançamento nos totais em euro.</small></label>}<label>Categoria<select name="cat"><option>Alimentação</option><option>Moradia</option><option>Transporte</option><option>Saúde</option><option>Lazer</option><option>Receita</option><option>Outros</option></select></label><ModalActions close={close} label="Adicionar lançamento"/></form></div>}
function Converter({close}){const[amount,setAmount]=useState(''),[rate,setRate]=useState(''),result=(Number(amount)||0)*(Number(rate)||0);return <div className="overlay"><div className="modal"><ModalHead title="Visualizar valor em reais" text="Esta simulação não altera a moeda principal nem salva dados." close={close}/><div className="converter-note"><b>EUR continua como moeda principal</b><span>Use a cotação que preferir para a consulta.</span></div><label>Valor em euro (EUR)<input autoFocus value={amount} onChange={e=>setAmount(e.target.value)} type="number" min="0" step="0.01" placeholder="0,00"/></label><label>Cotação — 1 EUR vale quantos BRL?<input value={rate} onChange={e=>setRate(e.target.value)} type="number" min="0" step="0.0001" placeholder="Ex.: 6,20"/></label><div className="conversion-result"><small>Valor estimado em reais</small><strong>{money(result,'BRL')}</strong><span>{amount&&rate?`${money(amount)} × ${Number(rate).toLocaleString('pt-BR')} BRL`:'Preencha os dois campos para visualizar'}</span></div><div className="modal-actions"><button onClick={close}>Fechar</button></div></div></div>}
function SimpleModal({type,save,close}){let copy={account:['Nova conta ou cartão','Nome da conta','Saldo inicial'],goal:['Nova meta','Nome da meta','Valor desejado'],budget:['Novo limite','Categoria','Limite mensal']}[type];return <div className="overlay"><form className="modal" onSubmit={save}><ModalHead title={copy[0]} text="Os valores deste item serão registrados em euro." close={close}/><label>{copy[1]}<input name="name" required autoFocus placeholder={type==='account'?'Ex.: Conta principal':'Ex.: Viagem'}/></label><label>{copy[2]} (EUR)<input name="value" required type="number" min="0" step="0.01" placeholder="0,00"/></label><ModalActions close={close} label="Salvar"/></form></div>}
function ModalHead({title,text,close}){return <div className="modal-head"><div><h2>{title}</h2><p>{text}</p></div><button type="button" onClick={close} aria-label="Fechar"><X/></button></div>}
function ModalActions({close,label}){return <div className="modal-actions"><button type="button" onClick={close}>Cancelar</button><button className="new">{label}</button></div>}
function Login({onLogin}){const[error,setError]=useState(''),[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setError('');let f=new FormData(e.currentTarget);try{let r=await fetch('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:f.get('username'),password:f.get('password')})});if(!r.ok)throw new Error();onLogin()}catch{setError('Usuário ou senha incorretos.')}finally{setBusy(false)}}return <div className="loginpage"><div className="loginart"><div className="brand"><span>m</span><b>Meu Fluxo</b></div><div><small>FINANÇAS SOB CONTROLE</small><h1>Clareza para decidir.<br/>Tranquilidade para viver.</h1><p>Acompanhe sua vida financeira de forma simples, privada e inteligente.</p></div><blockquote>“Um lugar seguro para transformar números em escolhas melhores.”</blockquote></div><form className="loginbox" onSubmit={submit}><p className="eyebrow">ÁREA PROTEGIDA</p><h2>Bem-vindo de volta</h2><p>Entre com seus dados para acessar seu painel.</p><label>Usuário<input name="username" required autoComplete="username" placeholder="Seu usuário"/></label><label>Senha<input name="password" required type="password" autoComplete="current-password" placeholder="Sua senha"/></label>{error&&<div className="loginerror">{error}</div>}<button className="loginbutton" disabled={busy}>{busy?'Entrando…':'Entrar com segurança'}</button><small className="secure">🔒 Conexão protegida e sessão segura</small></form></div>}
function Root(){const[status,setStatus]=useState('loading');useEffect(()=>{fetch('/api/session').then(r=>setStatus(r.ok?'in':'out')).catch(()=>setStatus('out'))},[]);async function logout(){await fetch('/api/logout',{method:'POST'});setStatus('out')}if(status==='loading')return <div className="splash"><div className="brand"><span>m</span><b>Meu Fluxo</b></div></div>;return status==='in'?<FinanceApp onLogout={logout}/>:<Login onLogin={()=>setStatus('in')}/>}createRoot(document.getElementById('root')).render(<Root/>);
