import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{LayoutDashboard,ArrowLeftRight,WalletCards,ChartPie,Target,Settings,Plus,Search,Bell,ChevronDown,TrendingUp,TrendingDown,Eye,EyeOff,X,Landmark,CreditCard,ShoppingBag,Home,Car,Utensils,HeartPulse,Plane,MoreHorizontal}from'lucide-react';
import'./style.css';

const currencies={BRL:{label:'Real brasileiro',symbol:'R$',locale:'pt-BR'},USD:{label:'Dólar americano',symbol:'US$',locale:'en-US'},EUR:{label:'Euro',symbol:'€',locale:'pt-PT'},GBP:{label:'Libra esterlina',symbol:'£',locale:'en-GB'},JPY:{label:'Iene japonês',symbol:'¥',locale:'ja-JP'}};
const seed=[
 {id:1,date:'Hoje, 06 out',name:'Supermercado Verde',cat:'Alimentação',type:'out',value:186.42,icon:'food'},
 {id:2,date:'Hoje, 06 out',name:'Salário',cat:'Receita',type:'in',value:6800,icon:'wallet'},
 {id:3,date:'Ontem, 05 out',name:'Posto Avenida',cat:'Transporte',type:'out',value:240,icon:'car'},
 {id:4,date:'04 out',name:'Streaming',cat:'Assinaturas',type:'out',value:39.9,icon:'shop'},
 {id:5,date:'03 out',name:'Farmácia Central',cat:'Saúde',type:'out',value:78.5,icon:'health'},
];
const iconMap={food:Utensils,wallet:WalletCards,car:Car,shop:ShoppingBag,health:HeartPulse,home:Home,travel:Plane};
function money(v,c){return new Intl.NumberFormat(currencies[c].locale,{style:'currency',currency:c,maximumFractionDigits:c==='JPY'?0:2}).format(v)}
function FinanceApp(){
 const[cur,setCur]=useState(localStorage.getItem('currency')||'BRL');const[show,setShow]=useState(true);const[modal,setModal]=useState(false);const[tx,setTx]=useState(()=>JSON.parse(localStorage.getItem('transactions')||'null')||seed);const[page,setPage]=useState('Visão geral');
 const total=useMemo(()=>tx.reduce((s,t)=>s+(t.type==='in'?t.value:-t.value),12450),[tx]);const income=tx.filter(x=>x.type==='in').reduce((s,x)=>s+x.value,0);const expense=tx.filter(x=>x.type==='out').reduce((s,x)=>s+x.value,0);
 const save=(e)=>{e.preventDefault();let f=new FormData(e.currentTarget);let next={id:Date.now(),date:'Hoje, 06 out',name:f.get('name'),cat:f.get('cat'),type:f.get('type'),value:Number(f.get('value')),icon:f.get('type')==='in'?'wallet':'shop'};let all=[next,...tx];setTx(all);localStorage.setItem('transactions',JSON.stringify(all));setModal(false)};
 const nav=[['Visão geral',LayoutDashboard],['Lançamentos',ArrowLeftRight],['Contas e cartões',WalletCards],['Planejamento',ChartPie],['Metas',Target]];
 return <div className="app"><aside><div className="brand"><span>m</span><b>Meu Fluxo</b></div><nav>{nav.map(([n,I])=><button className={page===n?'active':''} onClick={()=>setPage(n)}><I size={19}/>{n}</button>)}</nav><div className="aside-bottom"><div className="tip"><b>Organize seu futuro</b><small>Defina metas e acompanhe cada conquista.</small><button onClick={()=>setPage('Metas')}>Criar uma meta</button></div><button><Settings size={19}/>Configurações</button><div className="profile"><div>JS</div><span><b>Julio</b><small>Conta pessoal</small></span><MoreHorizontal size={18}/></div></div></aside>
 <main><header><div><h1>{page}</h1><p>Terça-feira, 6 de outubro</p></div><div className="header-actions"><div className="search"><Search size={18}/><input placeholder="Buscar lançamentos..."/></div><button className="iconbtn"><Bell size={19}/><i/></button><label className="currency"><span>{cur}</span><select value={cur} onChange={e=>{setCur(e.target.value);localStorage.setItem('currency',e.target.value)}}>{Object.entries(currencies).map(([k,v])=><option value={k}>{k} — {v.label}</option>)}</select><ChevronDown size={15}/></label><button className="new" onClick={()=>setModal(true)}><Plus size={18}/>Novo lançamento</button></div></header>
 <section className="content"><div className="welcome"><div><span>SEU RESUMO FINANCEIRO</span><h2>Olá, Julio! Seu dinheiro está<br/>trabalhando a seu favor.</h2></div><button className="period">Este mês <ChevronDown size={16}/></button></div>
 <div className="cards"><Card label="Saldo total" value={total} cur={cur} main show={show} onEye={()=>setShow(!show)} delta="8,4% este mês"/><Card label="Receitas" value={income} cur={cur} show={show} delta="12,5% vs. mês anterior" up/><Card label="Despesas" value={expense} cur={cur} show={show} delta="3,2% vs. mês anterior"/><Card label="Economia do mês" value={income-expense} cur={cur} show={show} delta={`${Math.max(0,Math.round((income-expense)/(income||1)*100))}% da sua renda`} up/></div>
 <div className="grid"><div className="panel cash"><div className="panel-head"><div><h3>Fluxo de caixa</h3><p>Receitas e despesas dos últimos 6 meses</p></div><button>Últimos 6 meses <ChevronDown size={14}/></button></div><div className="legend"><i className="green"/>Receitas <i className="coral"/>Despesas</div><div className="chart"><div className="yaxis"><span>8k</span><span>6k</span><span>4k</span><span>2k</span><span>0</span></div>{[['Mai',62,40],['Jun',70,49],['Jul',58,45],['Ago',77,51],['Set',68,46],['Out',84,38]].map(([m,a,b])=><div className="bars"><div><i style={{height:a+'%'}}/><i style={{height:b+'%'}}/></div><span>{m}</span></div>)}</div></div>
 <div className="panel categories"><div className="panel-head"><div><h3>Despesas por categoria</h3><p>Onde seu dinheiro foi usado</p></div><button><MoreHorizontal/></button></div><div className="donut"><div><b>100%</b><small>{money(expense,cur)}</small></div></div><ul>{[['Moradia','35%','#23423d'],['Alimentação','24%','#e97760'],['Transporte','18%','#eebd62'],['Saúde','13%','#7d9ea1'],['Outros','10%','#c8cec8']].map(x=><li><i style={{background:x[2]}}/><span>{x[0]}</span><b>{x[1]}</b></li>)}</ul></div></div>
 <div className="grid lower"><div className="panel transactions"><div className="panel-head"><div><h3>Últimos lançamentos</h3><p>Movimentações mais recentes</p></div><button className="link" onClick={()=>setPage('Lançamentos')}>Ver todos</button></div>{tx.slice(0,5).map(t=>{let I=iconMap[t.icon]||ShoppingBag;return <div className="row"><div className={'cat '+t.type}><I size={18}/></div><div className="txname"><b>{t.name}</b><small>{t.cat} · {t.date}</small></div><strong className={t.type}>{t.type==='in'?'+':'−'} {money(t.value,cur)}</strong></div>})}</div>
 <div className="panel budget"><div className="panel-head"><div><h3>Orçamento mensal</h3><p>Progresso por categoria</p></div><button className="link">Gerenciar</button></div>{[['Alimentação',820,1200,'68%'],['Transporte',540,800,'67%'],['Lazer',390,500,'78%']].map(([n,a,b,p])=><div className="progress"><span><b>{n}</b><small>{money(a,cur)} de {money(b,cur)}</small></span><div><i style={{width:p}}/></div></div>)}</div></div></section></main>
 {modal&&<div className="overlay"><form className="modal" onSubmit={save}><div className="modal-head"><div><h2>Novo lançamento</h2><p>Registre uma movimentação financeira.</p></div><button type="button" onClick={()=>setModal(false)}><X/></button></div><label>Descrição<input required name="name" placeholder="Ex.: Mercado, salário..." autoFocus/></label><div className="formgrid"><label>Tipo<select name="type"><option value="out">Despesa</option><option value="in">Receita</option></select></label><label>Valor ({cur})<input required name="value" type="number" min="0" step="0.01" placeholder="0,00"/></label></div><label>Categoria<select name="cat"><option>Alimentação</option><option>Moradia</option><option>Transporte</option><option>Saúde</option><option>Lazer</option><option>Receita</option><option>Outros</option></select></label><div className="modal-actions"><button type="button" onClick={()=>setModal(false)}>Cancelar</button><button className="new">Adicionar lançamento</button></div></form></div>}
 </div>}
function Card({label,value,cur,main,show,onEye,delta,up}){return <div className={'summary '+(main?'primary':'')}><div className="label">{label}{main&&<button onClick={onEye}>{show?<Eye size={17}/>:<EyeOff size={17}/>}</button>}</div><strong>{show?money(value,cur):'••••••'}</strong><small className={up?'positive':''}>{up?<TrendingUp size={14}/>:<TrendingDown size={14}/>} {delta}</small></div>}
function Login({onLogin}){const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function submit(e){e.preventDefault();setBusy(true);setError('');let f=new FormData(e.currentTarget);try{let r=await fetch('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({username:f.get('username'),password:f.get('password')})});if(!r.ok)throw new Error();onLogin()}catch{setError('Usuário ou senha incorretos.')}finally{setBusy(false)}}return <div className="loginpage"><div className="loginart"><div className="brand"><span>m</span><b>Meu Fluxo</b></div><div><small>FINANÇAS SOB CONTROLE</small><h1>Clareza para decidir.<br/>Tranquilidade para viver.</h1><p>Acompanhe sua vida financeira de forma simples, privada e inteligente.</p></div><blockquote>“Um lugar seguro para transformar números em escolhas melhores.”</blockquote></div><form className="loginbox" onSubmit={submit}><div className="mobilebrand"><span>m</span><b>Meu Fluxo</b></div><p className="eyebrow">ÁREA PROTEGIDA</p><h2>Bem-vindo de volta</h2><p>Entre com seus dados para acessar seu painel.</p><label>Usuário<input name="username" required autoComplete="username" placeholder="Seu usuário"/></label><label>Senha<input name="password" required type="password" autoComplete="current-password" placeholder="Sua senha"/></label>{error&&<div className="loginerror">{error}</div>}<button className="loginbutton" disabled={busy}>{busy?'Entrando…':'Entrar com segurança'}</button><small className="secure">🔒 Conexão protegida e sessão segura</small></form></div>}
function Root(){const[status,setStatus]=useState('loading');useEffect(()=>{fetch('/api/session').then(r=>setStatus(r.ok?'in':'out')).catch(()=>setStatus('out'))},[]);if(status==='loading')return <div className="splash"><div className="brand"><span>m</span><b>Meu Fluxo</b></div></div>;return status==='in'?<FinanceApp/>:<Login onLogin={()=>setStatus('in')}/>}
createRoot(document.getElementById('root')).render(<Root/>);
